MainWindow
Weather MainWindow::data_weather
Referenced by page_content, reload_data.
QString MainWindow::myURL
Referenced by check_for_an_update.
QString MainWindow::myURL1
Referenced by check_for_an_update1.
QString MainWindow::myURL2
Referenced by check_for_an_update2.
Ui::MainWindow* MainWindow::ui
Referenced by MainWindow, page1, page2, page3, page4, page_content, page_loading, ~MainWindow.
QGraphicsScene* MainWindow::scene
Referenced by page_content.
QTimer* MainWindow::timer
Referenced by page_content, page_loading.
QPropertyAnimation* MainWindow::animation
QPropertyAnimation* MainWindow::animation_button
MainWindow::MainWindow(QWidget *parent=nullptr)
MainWindow::MainWindow konstruktor głównego okna ustawia tło, inicjalizuje przyciski.
parent rodzic
References page1, page2, page3, page4, ui.
MainWindow::~MainWindow()
MainWindow::~MainWindow destruktor głównego okna.
References ui.
void MainWindow::reload_data(QNetworkReply *)
MainWindow::reload_data pobieranie danych z internetu za pomoca api.
reply zapytanie o dane
References Weather::cloudiness, data_weather, Weather::deg, Weather::description, Weather::gust, Weather::humidity, Weather::icon, Weather::pressure, Weather::speed, Weather::temp, Weather::temp_max, Weather::temp_min, Weather::temp_realfeel, Weather::visibility.
Referenced by check_for_an_update, check_for_an_update1, check_for_an_update2.
bool MainWindow::check_for_an_update()
MainWindow::check_for_an_update funkcja wywołująca zapytanie dla jeziora Żywieckiego.
[out] true po dostaniu odpowiedzi
References myURL, reload_data.
Referenced by page2.
bool MainWindow::check_for_an_update1()
MainWindow::check_for_an_update1 funkcja wywołująca zapytanie dla jeziora Roś
[out] true po dostaniu odpowiedzi
References myURL1, reload_data.
Referenced by page3.
bool MainWindow::check_for_an_update2()
MainWindow::check_for_an_update2 funkcja wywołująca zapytanie dla jeziora Konorowskiego.
[out] true po dostaniu odpowiedzi
References myURL2, reload_data.
Referenced by page4.
void MainWindow::page1()
MainWindow::page1 Strona główna połączenie przycisku z docelowym miejscem.
References page2, ui.
Referenced by MainWindow, page2, page3, page4.
void MainWindow::page2()
MainWindow::page2 strona jeziora Żywieckiego.
References check_for_an_update, page1, page_content, page_loading, ui.
Referenced by MainWindow, page1.
void MainWindow::page3()
MainWindow::page3 strona jeziora Roś
References check_for_an_update1, page1, page_content, page_loading, ui.
Referenced by MainWindow.
void MainWindow::page4()
MainWindow::page4 strona jeziora Konorowskiego.
References check_for_an_update2, page1, page_content, page_loading, ui.
Referenced by MainWindow.
void MainWindow::page_loading()
MainWindow::page_loading strona z napisem POBIERANIE DANYCH licznik czasu.
References timer, ui.
Referenced by page2, page3, page4.
void MainWindow::page_content()
MainWindow::page_content zawartosc strony szczegółowej tu znajduje się ustaniwenie napisów oraz wywołanie chmur.
References Weather::cloudiness, data_weather, Weather::deg, scene, Weather::speed, Weather::temp_realfeel, timer, ui.
Referenced by page2, page3, page4.